---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: assisted-service
  namespace: $REPLACE_NAMESPACE

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assisted-service
  namespace: $REPLACE_NAMESPACE
rules:
  - apiGroups:
    - ""
    - coordination.k8s.io
    resources:
    - configmaps
    - leases
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assisted-service
  namespace: $REPLACE_NAMESPACE
subjects:
- kind: ServiceAccount
  name: assisted-service
roleRef:
  kind: Role
  name: assisted-service
  apiGroup: rbac.authorization.k8s.io
