# ---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agentinstalladmission
  namespace: $REPLACE_NAMESPACE_L1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agentinstalladmission
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agentinstalladmission
subjects:
- kind: ServiceAccount
  name: agentinstalladmission
  namespace: $REPLACE_NAMESPACE_L1

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentinstalladmission
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
# Allow managedcluster admission to get/list/watch configmaps
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
# Allow managedcluster admission to create subjectaccessreviews
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
# API priority and fairness
- apiGroups:
  - flowcontrol.apiserver.k8s.io
  resources:
  - prioritylevelconfigurations
  - flowschemas
  verbs:
  - get
  - list
  - watch
